//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestão_Estoque.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gestão_Estoque.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_Add {
            get {
                object obj = ResourceManager.GetObject("Icon_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_Delete {
            get {
                object obj = ResourceManager.GetObject("Icon_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_Management {
            get {
                object obj = ResourceManager.GetObject("Icon_Management", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_Management2 {
            get {
                object obj = ResourceManager.GetObject("Icon_Management2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product_Amount.
        /// </summary>
        public static string Inventory_Amount_Column {
            get {
                return ResourceManager.GetString("Inventory_Amount_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product_Amount_UN.
        /// </summary>
        public static string Inventory_AmountUN_Column {
            get {
                return ResourceManager.GetString("Inventory_AmountUN_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Products_Date_Expiration.
        /// </summary>
        public static string Inventory_Date_Expiration_Column {
            get {
                return ResourceManager.GetString("Inventory_Date_Expiration_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product_ID.
        /// </summary>
        public static string Inventory_ID_Column {
            get {
                return ResourceManager.GetString("Inventory_ID_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product_Name.
        /// </summary>
        public static string Inventory_Name_Column {
            get {
                return ResourceManager.GetString("Inventory_Name_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product_Profit.
        /// </summary>
        public static string Inventory_Profit_Column {
            get {
                return ResourceManager.GetString("Inventory_Profit_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product_Profit_UN.
        /// </summary>
        public static string Inventory_ProfitUN_Column {
            get {
                return ResourceManager.GetString("Inventory_ProfitUN_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product_Quantity.
        /// </summary>
        public static string Inventory_Quantity_Column {
            get {
                return ResourceManager.GetString("Inventory_Quantity_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Products_Sold.
        /// </summary>
        public static string Inventory_Solds_Column {
            get {
                return ResourceManager.GetString("Inventory_Solds_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inventory_Management1.
        /// </summary>
        public static string Inventory_Table_Name {
            get {
                return ResourceManager.GetString("Inventory_Table_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a String_Category.
        /// </summary>
        public static string Lot_Category_Column {
            get {
                return ResourceManager.GetString("Lot_Category_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a String_Date_Expiration.
        /// </summary>
        public static string Lot_Date_Expiration_Column {
            get {
                return ResourceManager.GetString("Lot_Date_Expiration_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Int_ID.
        /// </summary>
        public static string Lot_ID_Column {
            get {
                return ResourceManager.GetString("Lot_ID_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a String_Product.
        /// </summary>
        public static string Lot_Name_Column {
            get {
                return ResourceManager.GetString("Lot_Name_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Decimal_Price_Lote.
        /// </summary>
        public static string Lot_Price_Lote_Column {
            get {
                return ResourceManager.GetString("Lot_Price_Lote_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Decimal_Total_Profit_Percentage.
        /// </summary>
        public static string Lot_Profit_Percentage_Column {
            get {
                return ResourceManager.GetString("Lot_Profit_Percentage_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Int_Quantity_Products.
        /// </summary>
        public static string Lot_Quatity_Products_Column {
            get {
                return ResourceManager.GetString("Lot_Quatity_Products_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a String_Stauts.
        /// </summary>
        public static string Lot_Status_Column {
            get {
                return ResourceManager.GetString("Lot_Status_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lots_Management.
        /// </summary>
        public static string Lot_Table_Name {
            get {
                return ResourceManager.GetString("Lot_Table_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Int_Number_Of_Units_Sold.
        /// </summary>
        public static string Lot_Units_Solds_Column {
            get {
                return ResourceManager.GetString("Lot_Units_Solds_Column", resourceCulture);
            }
        }
    }
}
